import type { Metadata } from "next"
import { Inter, Volkhov } from "next/font/google"

import "./styles/globals.css"

import { ThemeProvider } from "@/contexts/ThemeProvider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const volkhov = Volkhov({
  subsets: ["latin"],
  variable: "--font-volkhov",
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Alienzone | Oni",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${volkhov.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
